

# - Set to 0 to disable additional spawning of that mob.
# - A value of 0 equals 0%, a value of 1 equals 100%.
# - Note: Zombie Horses are normal animals and do not burn in daylight. Keep the spawn rate low if you don't want to
#   overfill your server.

# Spawnrate values
zombieHorseSpawnRate: 0.01
illusionerSpawnRate: 0.01
vindicatorSpawnRate: 0.03
evokerSpawnRate: 0.03
ravagerSpawnRate: 0.005
