

# - Set to 0 to disable additional spawning of that mob
# - Note: Zombie Horses are normal animals and do not burn in daylight. Keep the spawn rate low if you don't want to
#   overfill your server.

# Zombie Horses
zombieHorseSpawnRate: 1

# Illusioner
illusionerSpawnRate: 1

# Vindicator
vindicatorSpawnRate: 1

# Evocer
evocerSpawnRate: 1
